Bundle firmware updater with software store
ubuntu/app-store pull request #1143
Opened 2023-03-06 13:51 UTC by d-loose

- Adds [firmware-updater](https://github.com/canonical/firmware-updater) as a separate app within the snap
- Runs firmware-notifier periodically (every three hours)

2023-03-06 20:39 UTC, kenvandine requested changes
specify source-tag

2023-03-06 20:39 UTC, kenvandine commented on snap/snapcraft.yaml
> +    source: https://github.com/canonical/firmware-updater.git
add source-tag

2023-03-06 20:39 UTC, kenvandine commented on snap/snapcraft.yaml
> +    source: https://github.com/canonical/firmware-updater.git
add source-tag

2023-03-06 20:39 UTC, kenvandine commented on snap/snapcraft.yaml
> +    source: https://github.com/canonical/firmware-updater.git
add source-tag

2023-03-07 09:22 UTC, d-loose commented
There's no versioning scheme for the firmware updater yet - is it time to introduce one?
I've specified the latest commit for now.

2023-07-18 08:51 UTC, d-loose commented
Closing this for now. I'll rebase and reopen it later if we still want to ship the store and the firmware updater together.

2023-07-18 08:51 UTC, closed without merging